version: '3.8'

services:
  react-app:
    build:
      context: ./app-client
      dockerfile: Dockerfile
      args:  # ارسال متغیرها به Dockerfile
        - NODE_ENV=${NODE_ENV}
        - REACT_APP_API_URL=${REACT_APP_API_URL}
        - REACT_APP_API_KEY=${REACT_APP_API_KEY}
    image: i-react-compose:latest
    container_name: react-app-compose
    ports:
      - "${HOST_PORT}:${APP_PORT}"
    environment:  # متغیرهای محیطی برای کانتینر
      - NODE_ENV=${NODE_ENV}
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - REACT_APP_API_KEY=${REACT_APP_API_KEY}
      - REACT_APP_ENV=${REACT_APP_ENV}
      - REACT_APP_VERSION=${REACT_APP_VERSION}
      - REACT_APP_GOOGLE_MAPS_KEY=${REACT_APP_GOOGLE_MAPS_KEY}
      - REACT_APP_SENTRY_DSN=${REACT_APP_SENTRY_DSN}
      - REACT_APP_FEATURE_FLAG_NEW_DASHBOARD=${REACT_APP_FEATURE_FLAG_NEW_DASHBOARD}
      - REACT_APP_DEBUG_MODE=${REACT_APP_DEBUG_MODE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge